#!/bin/bash

[ -d target/ ] && rm -r target/

echo "Compiling TypeScript..."
yarn tsc || exit 1

cp -r migrations/ public/ views/ .env* target/
mkdir target/node_modules
mv target/pushrelay target/node_modules

echo "Starting..."
cd target/
node index
